"""add account model,and chores

Revision ID: 3f826e2d7e82
Revises: fa8bc6b3df8c
Create Date: 2025-10-28 12:01:23.904423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f826e2d7e82'
down_revision: Union[str, Sequence[str], None] = 'fa8bc6b3df8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('icon_bg_color', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('include_in_total', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.add_column('categories', sa.Column('icon_name', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('icon_bg_color', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'account_id')
    op.drop_column('categories', 'icon_bg_color')
    op.drop_column('categories', 'icon_name')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
