"""add relation in model user with resetpasswordtokens

Revision ID: 6f0bbf00f500
Revises: 44a1f76d2e4b
Create Date: 2025-10-02 14:05:30.858615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0bbf00f500'
down_revision: Union[str, Sequence[str], None] = '44a1f76d2e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
