"""add currency field in transaction

Revision ID: 8fccc71cd6f7
Revises: 3f826e2d7e82
Create Date: 2025-10-28 14:58:27.824496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fccc71cd6f7'
down_revision: Union[str, Sequence[str], None] = '3f826e2d7e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###
