"""add relation with type in model transaction

Revision ID: fa8bc6b3df8c
Revises: 6f0bbf00f500
Create Date: 2025-10-27 17:21:18.007736

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa8bc6b3df8c"
down_revision: Union[str, Sequence[str], None] = "6f0bbf00f500"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE transaction_type AS ENUM ('income', 'expense')")

    op.drop_column("categories", "type")

    op.add_column(
        "categories",
        sa.Column(
            "transaction_type",
            postgresql.ENUM("income", "expense", name="transaction_type"),
            nullable=False,
        ),
    )

    op.execute("DROP TYPE IF EXISTS category_type")

    op.add_column(
        "transactions",
        sa.Column(
            "transaction_type",
            postgresql.ENUM("income", "expense", name="transaction_type"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE category_type AS ENUM ('income', 'expense')")
    op.drop_column("transactions", "transaction_type")
    op.drop_column("categories", "transaction_type")
    op.add_column(
        "categories",
        sa.Column(
            "type",
            postgresql.ENUM("income", "expense", name="category_type"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute("DROP TYPE IF EXISTS transaction_type")
    # ### end Alembic commands ###
